### ISSUE TITLE
In some cases, explore by area could use a loading indicator.

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/imaginerio#140]
Not exactly sure where it would go. In the sidebar might be the obvious answer, but I could also see it swapping in for the search icon in the mode button itself.

**Comment by davidheyman** [comment]
The current imagineRio uses a loading GIF that gets placed at the cursor. To keep the users’s attention from flying all around, let’s either drop it on the map centered on the search box or where the search results will appear.
