### ISSUE TITLE
Make the back to legend button bigger

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/imaginerio#185]
This search/return to legend stuff it looking really good. One small change... Can we make the size of the button bigger? Maybe `font-size: 30px`, about the the size of the year stepper buttons above it.

![imaginerio](https://user-images.githubusercontent.com/4501388/41051368-8e6f8896-697b-11e8-8496-fa7a6b372a1c.png)

**Comment by bwellington** [comment]
Updated. Does the magnifying glass need to increase in size now, too? Looks a little strange having the "search map layers" text jump when clicked on.

**Comment by bcsheesley** [comment]
Jumping a little bit is okay, although I think this is more than necessary. Can you shift "Search map layers..." 15px to the left (to about where the red line is in this screenshot)? Maybe the "Return to legend" text can also be moved to that same position.

![screen shot 2018-06-11 at 9 50 56 am](https://user-images.githubusercontent.com/4501388/41239172-633eeac8-6d5d-11e8-824a-419e17da0c23.png)

**Comment by bcsheesley** [comment]
Could you make the back arrow button and "Return to Legend" text change to color #333 on hover and then close this one out? Thanks!
