### ISSUE TITLE
Make collector fields the same width and align left edges

### ISSUE THREAD

**Issue by davidheyman** [axismaps/imaginerio#193]

**Comment by kingfisher13** [comment]
I'm seeing equal-width collector fields that are left-aligned on Chrome, FF, Edge, and IE as well as Safari on BrowserStack. Did you mean full-width fields with the label sitting on top?

![image](https://user-images.githubusercontent.com/9831929/30884491-89f566f4-a2d5-11e7-8eee-f63223f991bf.png)

**Comment by davidheyman** [comment]
Must be Mac only:

![2017-09-27 at 14.46](http://static.gitscout.com/1411209fd0d404b99bafa9981ba6a8ba1340f46a8a5cf6265d0786363afd3141.png)
