### ISSUE TITLE
Update instituteRice and diverseLevant to run server-less

### ISSUE THREAD

**Issue by davidheyman** [axismaps/imaginerio#209]
There's no need for the client-side applications for both of these to run on an Express server.

@bwellington What's the best way to do this? I'm not concerned about packing the code but I would like to make sure we're only uploading what we need.

**Comment by bwellington** [comment]
At least for iRio, everything should be in the "dist" folder (after running `npm run build`).

**Comment by davidheyman** [comment]
Excellent. What would it take to move this functionality over to instituteRice and diverseLevant? I’m not as concerned about the code packing (having it is fine), but would definitely like the files copied over to a single directory that could then be uploaded.

**Comment by bwellington** [comment]
Looking at diverseLevant, I think all the files are in the `src` directory. Links to node_module libraries in `index.html` will need to change, though: right now express handles them (`<script src="jquery/dist/jquery.min.js"></script>`), so we'd need to copy those libraries into the `src` folder and link to them directly. This is what I did for iRio. Also, I think we could get rid of the `collector` folder/files.
